common_settings: &common_settings
  track_high_thresh: 0.25 # threshold for the first association
  track_low_thresh: 0.1 # threshold for the second association
  new_track_thresh: 0.25 # threshold for init new track if the detection does not match any tracks
  track_buffer: 30 # buffer to calculate the time when to remove tracks
  match_thresh: 0.8 # threshold for matching tracks
  fuse_score: True # whether we fuse confidence scores with the iou distances before matching

botsort:
  tracker_type: botsort
  <<: *common_settings
  gmc_method: sparseOptFlow # method of global motion compensation
  proximity_thresh: 0.5
  appearance_thresh: 0.25
  with_reid: False

bytetrack:
  tracker_type: bytetrack
  <<: *common_settings
